#!/bin/sh

CNET="cnet"

PARAMETERS1="-WNTqg -e30min"

#PARAMETERS2="-DNO_LOG -DMAX_CLIENTS_PER_AP=6"

PARAMETERS2="-DNO_LOG   -DMAX_CLIENTS_PER_AP=30  RESULT"


# recompile everything, just once
#
rm -rf *.cnet *.o
$CNET -nq `echo $PARAMETERS2`

# announce the simulation, and run it 5 times
#
echo cnet $PARAMETERS1 $PARAMETERS2
for i in 1 2 3 4 5
do
    $CNET `echo $PARAMETERS1 $PARAMETERS2` 
done
